# Generated by Django 3.1.7 on 2021-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
