# Generated by Django 3.1.7 on 2021-08-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Views',
        ),
        migrations.AddField(
            model_name='topic',
            name='Views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
